project:
  type: website
  output-dir: docs

website:
  title: "Sven Van Bael"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
      - text: Data science experience
        href: DatSciExp.qmd

format:
  html:
    theme: cosmo
    highlight-style: vim-dark
    css: styles.css
    toc: true

editor: visual

