project:
  type: website
  output-dir: docs

website:
  title: "Sven Van Bael"
  search: false
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Personal projects
        href: Personal_projects/personal_projects.qmd
      - text: Academic work
        href: Academic_work/academic_work.qmd

format:
  html:
    theme: cosmo
    highlight-style: "tango"
    css: styles.css
    toc: true

editor: visual

