project:
  type: website
  output-dir: docs

website:
  title: "Sven Van Bael"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
      - text: Personal data science projects
        href: Personal_data_science_projects/dataprojects.qmd
      - text: Academic work
        href: Academic_work/academicwork.qmd

format:
  html:
    theme: cosmo
    highlight-style: "tango"
    css: styles.css
    toc: true

editor: visual

